name: Build & Create Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET 6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      - name: Restore
        run: dotnet restore

      - name: Set secret
        run: |
          [xml]$xmlDoc = Get-Content ./anidow/Properties/Resources.resx
          $xmlDoc.SelectSingleNode("//root/data[@name='AppCenter_Secret']").Value = "${{ secrets.APPCENTER_SECRET }}"
          $xmlDoc.Save('./anidow/Properties/Resources.resx')

      - name: Generate licenses.json
        run: |
          ./GenerateLicenseFile.ps1

      - name: Publish self-contained
        run: dotnet publish --no-restore --configuration Release --self-contained true --runtime win-x64 --output windows/self-contained

      - name: Publish framework-dependent
        run: dotnet publish --no-restore --configuration Release --self-contained false --runtime win-x64 --output windows/framework-dependent

      - name: zip win artifact self-contained
        run: |
          powershell Compress-Archive windows/self-contained/anidow.exe windows/self-contained/anidow-full.zip

      - name: zip win artifact framework-dependent
        run: |
          powershell Compress-Archive windows/framework-dependent/anidow.exe windows/framework-dependent/anidow.zip

      - name: Upload artifact self-contained
        uses: actions/upload-artifact@v2
        with:
          name: anidow-full.zip
          path: windows/self-contained/anidow-full.zip

      - name: Upload artifact framework-dependent
        uses: actions/upload-artifact@v2
        with:
          name: anidow.zip
          path: windows/framework-dependent/anidow.zip

  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: anidow-full.zip
          path: windows/self-contained

      - uses: actions/download-artifact@v2
        with:
          name: anidow.zip
          path: windows/framework-dependent

      - name: Display structure of downloaded files
        run: ls -R
        working-directory: windows

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            windows/self-contained/anidow-full.zip
            windows/framework-dependent/anidow.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
